-- V015 DevSeed
-- Seeds one Customer, two Users, two Profiles, and all linkage for local development.
-- Password for all dev users: "dev123"
-- Hash algorithm: PBKDF2/SHA-512, 100 000 iterations, 64-byte hash, 32-byte salt.
--
-- Idempotent: all inserts are guarded by IF NOT EXISTS on Name/Email checks.
-- Safe to re-run. Does NOT modify rows that already exist.
--
-- DO NOT run this in production (guarded by environment in DatabaseMigrator if needed).

SET NOCOUNT ON;

-- -------------------------------------------------------------------------
-- Customer: Testkommune
-- -------------------------------------------------------------------------
DECLARE @CustomerId INT;

IF NOT EXISTS (SELECT 1 FROM [dbo].[Customers] WHERE [Name] = 'Testkommune')
BEGIN
    INSERT INTO [dbo].[Customers] ([Name])
    VALUES ('Testkommune');
END;

SELECT @CustomerId = [Id] FROM [dbo].[Customers] WHERE [Name] = 'Testkommune';

-- -------------------------------------------------------------------------
-- Users
-- Password: "dev123"
-- Hash/Salt generated by PasswordHasher (PBKDF2/SHA-512, 100 000 iterations)
-- -------------------------------------------------------------------------
DECLARE @AdminId INT, @SenderId INT;

IF NOT EXISTS (SELECT 1 FROM [dbo].[Users] WHERE [Email] = 'admin@dev.local')
BEGIN
    INSERT INTO [dbo].[Users] ([Email], [PasswordHash], [PasswordSalt], [IsActive])
    VALUES (
        'admin@dev.local',
        'jX4HKkXh60GLPYnd5RBku7PVbsF6Oijuerfd4/zV6LeF2QpsvE9ysH7Jyl0kRY7IJR0ctlaseEh64iuCdQVKfw==',
        'fLKlYkEcWwpdIAH+Wkx1CXFg1CD0c/rMiKc/RFTmyqg=',
        1
    );
END;

SELECT @AdminId = [Id] FROM [dbo].[Users] WHERE [Email] = 'admin@dev.local';

IF NOT EXISTS (SELECT 1 FROM [dbo].[Users] WHERE [Email] = 'sender@dev.local')
BEGIN
    INSERT INTO [dbo].[Users] ([Email], [PasswordHash], [PasswordSalt], [IsActive])
    VALUES (
        'sender@dev.local',
        'jX4HKkXh60GLPYnd5RBku7PVbsF6Oijuerfd4/zV6LeF2QpsvE9ysH7Jyl0kRY7IJR0ctlaseEh64iuCdQVKfw==',
        'fLKlYkEcWwpdIAH+Wkx1CXFg1CD0c/rMiKc/RFTmyqg=',
        1
    );
END;

SELECT @SenderId = [Id] FROM [dbo].[Users] WHERE [Email] = 'sender@dev.local';

-- -------------------------------------------------------------------------
-- UserCustomerMemberships
-- -------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM [dbo].[UserCustomerMemberships] WHERE [UserId] = @AdminId  AND [CustomerId] = @CustomerId)
    INSERT INTO [dbo].[UserCustomerMemberships] ([UserId], [CustomerId], [LanguageId]) VALUES (@AdminId,  @CustomerId, 1);

IF NOT EXISTS (SELECT 1 FROM [dbo].[UserCustomerMemberships] WHERE [UserId] = @SenderId AND [CustomerId] = @CustomerId)
    INSERT INTO [dbo].[UserCustomerMemberships] ([UserId], [CustomerId], [LanguageId]) VALUES (@SenderId, @CustomerId, 1);

-- -------------------------------------------------------------------------
-- UserRoles — give admin ManageUsers + ManageProfiles + CustomerSetup
-- -------------------------------------------------------------------------
DECLARE @RoleManageUsers    INT = (SELECT [Id] FROM [dbo].[UserRoles] WHERE [Name] = 'ManageUsers');
DECLARE @RoleManageProfiles INT = (SELECT [Id] FROM [dbo].[UserRoles] WHERE [Name] = 'ManageProfiles');
DECLARE @RoleCustomerSetup  INT = (SELECT [Id] FROM [dbo].[UserRoles] WHERE [Name] = 'CustomerSetup');

IF @RoleManageUsers IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [dbo].[UserRoleMappings] WHERE [UserId] = @AdminId AND [UserRoleId] = @RoleManageUsers)
    INSERT INTO [dbo].[UserRoleMappings] ([UserId], [UserRoleId]) VALUES (@AdminId, @RoleManageUsers);

IF @RoleManageProfiles IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [dbo].[UserRoleMappings] WHERE [UserId] = @AdminId AND [UserRoleId] = @RoleManageProfiles)
    INSERT INTO [dbo].[UserRoleMappings] ([UserId], [UserRoleId]) VALUES (@AdminId, @RoleManageProfiles);

IF @RoleCustomerSetup IS NOT NULL AND NOT EXISTS (SELECT 1 FROM [dbo].[UserRoleMappings] WHERE [UserId] = @AdminId AND [UserRoleId] = @RoleCustomerSetup)
    INSERT INTO [dbo].[UserRoleMappings] ([UserId], [UserRoleId]) VALUES (@AdminId, @RoleCustomerSetup);

-- -------------------------------------------------------------------------
-- Profiles
-- -------------------------------------------------------------------------
DECLARE @Profile1Id INT, @Profile2Id INT;

IF NOT EXISTS (SELECT 1 FROM [dbo].[Profiles] WHERE [CustomerId] = @CustomerId AND [DisplayName] = 'Nordjylland')
BEGIN
    INSERT INTO [dbo].[Profiles] ([CustomerId], [DisplayName])
    VALUES (@CustomerId, 'Nordjylland');
END;

SELECT @Profile1Id = [Id] FROM [dbo].[Profiles] WHERE [CustomerId] = @CustomerId AND [DisplayName] = 'Nordjylland';

IF NOT EXISTS (SELECT 1 FROM [dbo].[Profiles] WHERE [CustomerId] = @CustomerId AND [DisplayName] = 'Sønderjylland')
BEGIN
    INSERT INTO [dbo].[Profiles] ([CustomerId], [DisplayName])
    VALUES (@CustomerId, 'Sønderjylland');
END;

SELECT @Profile2Id = [Id] FROM [dbo].[Profiles] WHERE [CustomerId] = @CustomerId AND [DisplayName] = 'Sønderjylland';

-- -------------------------------------------------------------------------
-- ProfileUserMappings — admin gets Nordjylland only (1 profile → login auto-resolves full JWT)
-- Sønderjylland not mapped to admin: 2 profiles triggers RequiresProfileSelection in LoginHandler.
-- CustomerAdmin profiles list still shows both profiles (queried by CustomerId, not UserId).
-- -------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM [dbo].[ProfileUserMappings] WHERE [ProfileId] = @Profile1Id AND [UserId] = @AdminId)
    INSERT INTO [dbo].[ProfileUserMappings] ([ProfileId], [UserId]) VALUES (@Profile1Id, @AdminId);

IF NOT EXISTS (SELECT 1 FROM [dbo].[ProfileUserMappings] WHERE [ProfileId] = @Profile1Id AND [UserId] = @SenderId)
    INSERT INTO [dbo].[ProfileUserMappings] ([ProfileId], [UserId]) VALUES (@Profile1Id, @SenderId);
